import { create } from "zustand";
import { useDashboardSidebarHooks } from "../dashboard_hooks/useDahboardSidebarHooks";

export type TabType = "device_list" | "ai_reports" | "settings";

export const tabTypeToTitle: {
      [key in TabType]: string
} = {
      ai_reports: "AI Reports",
      device_list: "Device List",
      settings: "Settings"
}

export const tabTypeToDescription: {
      [key in TabType]: string
} = {
      ai_reports: "Reports generated by AI",
      device_list: "A list of connected devices",
      settings: ""
}

type useDashboardHooksType = {
      currentTab: TabType;
      setCurrentTab: (newTab: TabType) => void;
};

export const useDashboardHooks = create<useDashboardHooksType>((set) => ({
      currentTab: "device_list",
      setCurrentTab(newTab) {
            const { setOpen } = useDashboardSidebarHooks.getState();
            setOpen(false);

            set(() => ({
                  currentTab: newTab,
            }));
      },
}));
