import { create } from "zustand";
import { useDashboardSidebarHooks } from "../dashboard_hooks/useDahboardSidebarHooks";
import { createJSONStorage, persist } from "zustand/middleware";

export type TabType = "device_list" | "ai_reports" | "ai_chatbot" | "settings";

export const tabTypeToTitle: {
      [key in TabType]: string
} = {
      device_list: "Device List",
      ai_reports: "AI Reports",
      ai_chatbot: "AI Chatbot",
      settings: "Settings"
}

export const tabTypeToDescription: {
      [key in TabType]: string
} = {
      device_list: "A list of connected devices",
      ai_reports: "Reports generated by AI",
      ai_chatbot: "Ask anything about your aquaponics!",
      settings: ""
}

type useDashboardHooksType = {
      currentTab: TabType;
      setCurrentTab: (newTab: TabType) => void;
};

export const useDashboardHooks = create<useDashboardHooksType>()(
      persist(
            (set) => ({
                  currentTab: "device_list",
                  setCurrentTab(newTab) {
                        const { setOpen } = useDashboardSidebarHooks.getState();
                        setOpen(false);

                        set(() => ({
                              currentTab: newTab,
                        }));
                  },
            }),
            {
                  name: "gaia-dashboard-data",
                  storage: createJSONStorage(() => sessionStorage)
            }
      )
);
